services:
    app.repository.product:
        class: AppBundle\Repository\ProductRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: [AppBundle\Entity\Product]
